<a href="https://colab.research.google.com/github/singhbhupender1/ML-notebooks/blob/master/ntroduction_to_Vector_Norms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Vector Norm
**Calculating the size or length of a vector is often required either directly or as part of a broader vector or vector-matrix operation.**

**The length of the vector is referred to as the vector norm or the vectThe length of the vector is always a positive number, except for a vector of all zero values. It is calculated using some measure that summarizes the distance of the vector from the origin of the vector space. For example, the origin of a vector space for a vector with 3 elements is (0, 0, 0).**

**Notations are used to represent the vector norm in broader calculations and the type of vector norm calculation almost always has its own unique notation.or’s magnitude.**


##Vector L1 Norm
**The length of a vector can be calculated using the L1 norm, where the 1 is a superscript of the L, e.g. L^1.**

**The notation for the L1 norm of a vector is ||v||1, where 1 is a subscript. As such, this length is sometimes called the taxicab norm or the Manhattan norm.**

**The L1 norm is calculated as the sum of the absolute vector values, where the absolute value of a scalar uses the notation |a1|. In effect, the norm is a calculation of the Manhattan distance from the origin of the vector space.**



```
||v||1 = |a1| + |a2| + |a3|
```
**The L1 norm is often used when fitting machine learning algorithms as a regularization method, e.g. a method to keep the coefficients of the model small, and in turn, the model less complex.**


**The L1 norm of a vector can be calculated in NumPy using the norm() function with a parameter to specify the norm order, in this case 1.**

**First, a 1×3 vector is defined, then the L1 norm of the vector is calculated.**

In [1]:
#L1 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


##Vector L2 Norm
**The length of a vector can be calculated using the L2 norm, where the 2 is a superscript of the L, e.g. L^2.**

**The notation for the L2 norm of a vector is ||v||2 where 2 is a subscript.**

**The L2 norm calculates the distance of the vector coordinate from the origin of the vector space. As such, it is also known as the Euclidean norm as it is calculated as the Euclidean distance from the origin. The result is a positive distance value.**


```
||v||2 = sqrt(a1^2 + a2^2 + a3^2)
```



**The L2 norm is calculated as the square root of the sum of the squared vector values.**

**The L2 norm of a vector can be calculated in NumPy using the norm() function with default parameters.**

In [2]:
#l2 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


**Like the L1 norm, the L2 norm is often used when fitting machine learning algorithms as a regularization method, e.g. a method to keep the coefficients of the model small and, in turn, the model less complex.**

**By far, the L2 norm is more commonly used than other vector norms in machine learning.**

##Vector Max Norm

**The length of a vector can be calculated using the maximum norm, also called max norm.**

**Max norm of a vector is referred to as L^inf where inf is a superscript and can be represented with the infinity symbol. The notation for max norm is ||x||inf, where inf is a subscript.**



```
||v||inf = max(|a1|, |a2|, |a3|)
```



In [4]:
#max norm of a vector
from numpy import inf
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
#order parameter set to inf
maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0
