<a href="https://colab.research.google.com/github/singhbhupender1/ML-notebooks/blob/master/Python_Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version

Python 3.6.9


#Basic data types

In [2]:
x =3 
print(type(x)) #print the the data type
print(x) #prints the value
print(x +1) #prints the addition
print(x - 1) # prints the subtraction
print(x * 2) #prints the multiplication
print(x ** 2) #prints the exponential
x += 1 
print(x) #prints the updated value after adding 1 to x
x *= 2
print(x) #the updated value of x after multiplying 2


<class 'int'>
3
4
2
6
9
4
8


**Booleans**

In [3]:
t = True
f = False
print(type(t)) # prints class type of t
print(t and f) #logical 'and' of t and f
print(t or f) #logical 'or' of t and f
print(not t) #logical opposite of t
print(t != f) #logical XOR or if the condition is true or not

<class 'bool'>
False
True
False
True


**Strings**

In [4]:
hello = 'hello'
world = 'world'
print(hello) #prints value the value hello holds
print(len(hello)) #prints the lenth of string
hw = hello +  ' ' + world
print(hw)
hw12 = '%s %s %d' % (hello, world, 12) #sprintf style string formatting
print(hw12)
print(type(hello))

hello
5
hello world
hello world 12
<class 'str'>


In [6]:
s= 'hello'
print(s.capitalize())
print(s.upper())
print(s.rjust(7)) #right justifies with space padding with the value given
print(s.center(7)) #center justification with spacing on both sides
print(s.replace('l', ('ello'))) # replaces instaces of the substring with the given string
print(' world '.strip()) #strip leading and trailing whitspaces

Hello
HELLO
  hello
 hello 
heelloelloo
world


##containers

**Lists**
**A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:**

In [8]:
nums  = list(range(5)) #creates a list of intergers
print(nums) #prints value in the list
print(nums[2:4]) #prints a slice of values from 2 to 4(exlusive)
print(nums[2:]) #prints value from index 2 to the end
print(nums[:2]) #prints value from start till 2(exclusive)
print(nums[:]) #prints slice of whole list
print(nums[:-1]) #indexing from the start towars hte last
nums[2:4] = [8,9] #assign new value ot a slice
print(nums)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


**Loops**

In [9]:
animals = ['cats', 'dog', 'monkey']
for animal in animals:
  print(animal)

cats
dog
monkey


**If you want access to the index of each element within the body of a loop, use the built-in enumerate function:**

In [11]:
animals = ['cats', 'dog', 'monkey']
for idx, animal in enumerate(animals):
  print('#%d, %s' % (idx + 1, animal))


#1, cats
#2, dog
#3, monkey


**List comprehensions: When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:**

In [12]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
  squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


**You can make this code simpler using a list comprehension:**

In [13]:
nums = [0, 1 ,2, 3, 4]
sqaures = [x ** 2 for x in nums]
print(sqaures)


[0, 1, 4, 9, 16]


**List comprehensions can also contain conditions:**

In [15]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2  for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


##Dictionaries
**A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript. You can use it like this:**

In [17]:
d = {'cat': 'cute', 'dog' : 'furry'}
print(d['cat']) #prints value of the key
print('cat' in d) #checks if dictionary has key or not
d['fish'] = 'wet' #add new ket value pair in dic
print(d['fish'])
print(d.get('monkey', 'N/A')) #get an element with a default
print(d.get('fish', 'N/A')) #gets default value
del d['fish']
print(d.get('fish', 'N/A')) #as the key is no longer there so prints 'N/A'

cute
True
wet
N/A
wet
N/A


**Loops: It is easy to iterate over the keys in a dictionary:**

In [20]:
d = {'person' : 2, 'cat': 4, 'spider': 8}
for animal in d:
  legs = d[animal]
  print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


**If you want access to keys and their corresponding values, use the items method:**

In [24]:
d = {'person' : 2, 'cat': 4, 'spider': 8}
for animals, legs in d.items():
  print('A  %s has %d legs' % (animals, legs))

A  person has 2 legs
A  cat has 4 legs
A  spider has 8 legs


**Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:**

In [27]:
nums = [0, 1, 2 , 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 ==0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


##Sets
**A set is an unordered collection of distinct elements. As a simple example, consider the following:**

In [28]:
animals = {'cat', 'dog'}
print('cat' in animals) # checks if an element is in a set or not
animals.add('fish')
print('fish' in animals)
print(len(animals)) #no of animals in a set
print(animals.add('cat')) #adding an already present element does nothing
animals.remove('cat') #removes an element
print(len(animals))
print(animals)


True
True
3
None
2
{'dog', 'fish'}


**Loops: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:**

In [29]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
  print('#%d: %s' % (idx, animal))

#0: cat
#1: dog
#2: fish


**Set comprehensions: Like lists and dictionaries, we can easily construct sets using set comprehensions:**

In [30]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)

{0, 1, 2, 3, 4, 5}


##Tuples
**A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:**

In [32]:
d = {(x, x +1) : x for x in range(10)} #create a dic with tuple keys
t = (5, 6) # create a tuple
print(type(t)) 
print(d[t]) #access value of key in dic
print(d[(1, 2)]) # access values with tuple of keys


<class 'tuple'>
5
1


##Function
**Python functions are defined using the def keyword. For example:**

In [33]:
def sign(x):
  if x > 0:
    return 'positive'
  elif x < 0:
    return 'negavtive'
  else:
    return 'zero'

for x in [-1, 0, 1]:
  print(sign(x))

negavtive
zero
positive


**We will often define functions to take optional keyword arguments, like this:**

In [34]:
def hello(name, loud=False):
  if loud:
    print('Hello, %s!' % name.upper())
  else:
    print('Hello, %s!' %name)

hello('bob')
hello('bob', True)

Hello, bob!
Hello, BOB!


##Classes

In [38]:
class Greeter(object):
  #constructor
  def __init__(self, name):
    self.name = name #create an instance variable

  #instance method
  def greet(self, loud=False):
    if loud:
      print('Hello, %s!' % self.name.upper())
    else:
      print('Hello, %s!' % self.name)

g = Greeter('Fred') #  construct an instance of the class
g.greet() #call an instanc method
g.greet(True)

Hello, Fred!
Hello, FRED!


##Numpy
**Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.**

**Arrays**

**A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.**

**We can initialize numpy arrays from nested Python lists, and access elements using square brackets:**

In [39]:
import numpy as np
a = np.array([1, 2, 3]) ## create a rank 1 array
print(type(a))
print(a.shape) #prints shape of array
print(a[0], a[2]) # access elemets of an array
a[0] = 5 #change value of an element
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]]) #create a rank 2 array
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
1 3
[5 2 3]
(2, 3)
1 2 4


**Numpy also provides many functions to create arrays:**

In [40]:
import numpy as np
a = np.zeros((2, 2)) # create an array of all zeros
print(a)

b = np.ones((1, 2)) # create an arry of all ones
print(b)

c = np.full((2, 2), 7) #create an array of constant vlaues
print(c)

d = np.eye(2) #create a 2x2 indentity matrix
print(d)

e = np.random.random((2, 2)) # create an array filled with random values
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.09049201 0.50905179]
 [0.17325186 0.55534183]]


##Array indexing

**Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:**

In [41]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a[:2, 1:3] #use slicing to pull out subarray consiting of first 2 rows and columns 1 and 2, b has shaep 2X2:

#a slice of array is a view of the original data, so modifying it will modiy the orifinal data
print(a[0, 1]) #first row and 2 columns
b[0, 0] = 27 # it has same piece of data as a[0, 1]
print(a[0, 1])

2
27


**You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.**

In [43]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
#using only sices yields an array of same rank as the original array
row_r1 = a[1, :] #rank 1 view of the second row of a
row_r2 = a[1:2, :] #rank 2 view of second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

#we can make same disctinctions when accessing colums of an array:
col_r1 = a[:, 1] #rank 1 view of the sencond column  of array
col_r2 = a[:, 1:2] #rank 2 view of second column of array
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:**

In [45]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
#example of integer array indexing
#the resulting array wil have shape(3,)
print(a[[0, 1, 2], [0, 1, 0]])

#the above example of integer array indexing is equivalent ot this:
print(np.array([a[0, 0], a[1, 1] , a[2, 0]]))

#when using integer array indexing, you can reuse the same
#element from the source array
print(a[[0, 0], [1, 1]])

#equivalent to the previosu integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


**One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:**

In [46]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

#create an array of indices
b = np.array([0 , 2, 0, 1])
#select one element from each row of 'a' using the indices of 'b'
print(a[np.arange(4), b])

#mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


##Datatypes

**Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:**

In [49]:
import numpy as np

x  = np.array([1, 2]) #lets numpy choose the dataytype
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x= np.array([1, 2], dtype=np.int64) #force a particular datatype
print(x.dtype)

int64
float64
int64


##Array math

**Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:**

In [51]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

#element wise sum; both produce the array
print(x + y)
print(np.add(x, y))

#element wise difference 
print(x - y)
print(np.subtract(x, y))

#element wise product
print(x * y)
print(np.multiply(x, y))

#element wise divison
print(x / y)
print(np.divide(x, y))
#elementwise square root
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


**use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:**

In [53]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v= np.array([9, 10])
w = np.array([11, 12])

 #inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

#matrix/ vector product; both produce rank 1 array
print(x.dot(v))
print(np.dot(x, v))

#matrix/ matrix product; both produce rank 2 array
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


**Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:**

In [54]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

print(np.sum(x))
print(np.sum(x, axis=0)) #compute sum of each column
print(np.sum(x, axis=1)) #compute sum of each row

10
[4 6]
[3 7]


**Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:**

In [55]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)



[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


##Broadcasting

**Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.**

**For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:**

In [58]:
import numpy as np
#adding the vector v to each row of the matrix x,
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10 ,11, 12]])
v= np.array([1, 0, 1])
y= np.empty_like(x) #create empty matrix with same shape as x

#add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
  y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


**broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:**

In [59]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np. array([1, 0 ,1])
y = x + v #add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


**The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.**

**Broadcasting two arrays together follows these rules:**

**If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.**

**The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.**

**The arrays can be broadcast together if they are compatible in all dimensions.**

**After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.**

**In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension**

In [0]:
import numpy as np
v = np.array([1, 2, 3])
w = np.array([4, 5])
#to compute an outer product, we first reshape v to a column
#vector of shape(3, 1); we can broadast it against w to yield
#an output of shape (3, 2), which is the outer prodcut of v and w

print(np.reshape(v, (3, 1) * w))
#add a vector to each row of a matrix
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x + v)

